# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(472, 385)
        self.pushButton_login = QtWidgets.QPushButton(Form_login)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 320, 93, 28))
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_cancel = QtWidgets.QPushButton(Form_login)
        self.pushButton_cancel.setGeometry(QtCore.QRect(260, 320, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.TextLabel_Account = QtWidgets.QLabel(Form_login)
        self.TextLabel_Account.setGeometry(QtCore.QRect(60, 140, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TextLabel_Account.setFont(font)
        self.TextLabel_Account.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TextLabel_Account.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel_Account.setObjectName("TextLabel_Account")
        self.TextLabel_Password = QtWidgets.QLabel(Form_login)
        self.TextLabel_Password.setGeometry(QtCore.QRect(60, 200, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TextLabel_Password.setFont(font)
        self.TextLabel_Password.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel_Password.setObjectName("TextLabel_Password")
        self.lineEdit_Account = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_Account.setGeometry(QtCore.QRect(180, 140, 165, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Account.setFont(font)
        self.lineEdit_Account.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_Account.setText("")
        self.lineEdit_Account.setObjectName("lineEdit_Account")
        self.lineEdit_Password = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_Password.setGeometry(QtCore.QRect(180, 200, 165, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.TextLabel_Title = QtWidgets.QLabel(Form_login)
        self.TextLabel_Title.setGeometry(QtCore.QRect(120, 60, 198, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TextLabel_Title.setFont(font)
        self.TextLabel_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel_Title.setObjectName("TextLabel_Title")

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "登录"))
        self.pushButton_login.setText(_translate("Form_login", "登录"))
        self.pushButton_cancel.setText(_translate("Form_login", "取消"))
        self.TextLabel_Account.setText(_translate("Form_login", "用户名"))
        self.TextLabel_Password.setText(_translate("Form_login", "密码"))
        self.lineEdit_Account.setPlaceholderText(_translate("Form_login", "Admin"))
        self.lineEdit_Password.setPlaceholderText(_translate("Form_login", "password"))
        self.TextLabel_Title.setText(_translate("Form_login", "学生管理系统"))
