# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(80, 90, 113, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(30, 90, 55, 16))
        self.label_1.setObjectName("label_1")
        self.Title = QtWidgets.QLabel(Form)
        self.Title.setGeometry(QtCore.QRect(170, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Title.setFont(font)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setObjectName("Title")
        self.Button_Cancel = QtWidgets.QPushButton(Form)
        self.Button_Cancel.setGeometry(QtCore.QRect(290, 240, 75, 24))
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.Button_OK = QtWidgets.QPushButton(Form)
        self.Button_OK.setGeometry(QtCore.QRect(210, 240, 75, 24))
        self.Button_OK.setObjectName("Button_OK")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 55, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 120, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "字段1"))
        self.Title.setText(_translate("Form", "输入"))
        self.Button_Cancel.setText(_translate("Form", "取消"))
        self.Button_OK.setText(_translate("Form", "确定"))
        self.label_2.setText(_translate("Form", "字段2"))
